#!/bin/bash

CUR_DIR=$(cd $(dirname ${BASH_SOURCE[0]}); pwd)
BOARD=$(cat /etc/orangepi-release | grep BOARD= | cut -d= -f2)
SYSROOT=/campi/board/${BOARD}
CAMPI_ORDER_SVCS=("nmq" "cpi" "sys" "api" "gst")
LD_LIBRARY_PATH=${SYSROOT}/lib:${LD_LIBRARY_PATH}
PATH=${SYSROOT}/bin:${PATH}
PYTHONPATH=/campi:$PYTHONPATH

WIRELESS_ADAPTER=wlan0
DEFAULT_WIFI_SSID="hzcs211"
DEFAULT_WIFI_PASS="Mxjmxj211"
