#!/bin/bash

BOARD=$(cat /etc/orangepi-release | grep BOARD= | cut -d= -f2)
ADDRESS=$(cat /sys/class/net/eth0/address | sed 's/://g')

CAMPI_ORDER_SVCS=("nmq" "emq" "cpi" "sys" "api")

SYSROOT=/campi/board/${BOARD}
LD_LIBRARY_PATH=${SYSROOT}/lib:${LD_LIBRARY_PATH}
PATH=${SYSROOT}/bin:${PATH}
PYTHONPATH=/campi:.

RUNTIME_PATH=/campi/runtime
LOGS_PATH=/campi/logs

WIRELESS_ADAPTER=wlan0
DEFAULT_WIFI_SSID="hzcsdata"
DEFAULT_WIFI_PASS="Hzcsai@123"

__led_blink() {
    color=$1
    count=${2:-3}
    while (( count > 0 ))
    do
        sysled --color black
        sleep 1
        sysled --color ${color}
        (( count -= 1 ))
    done
}
